config/routes.rb
Rails.application.routes.draw do

  root 'places#index'
  resources :places, only: [:index, :show]
  get 'photos/:id/show', to: 'photos#show', as: 'photos_show'

end

app/models/place.rb
class Place
	include ActiveModel::Model
	attr_accessor :id, :formatted_address, :location, :address_components

	def initialize(params= {})
		
		@id=params[:_id].to_s
		@formatted_address = params[:formatted_address]
		@location = Point.new(params[:geometry][:geolocation])
		if !params[:address_components].nil?
			@address_components = []
			params[:address_components].each do |r|
				@address_components.push(AddressComponent.new(r))
			end
		end
	end
	
	def persisted?
	    !@id.nil?
	end

	def self.mongo_client
		Mongoid::Clients.default
	end

	def self.collection
		mongo_client['places']
	end

	def self.load_all (file)
		
		data= JSON.parse(file.read)
		collection.insert_many(data)
	end

	def self.find_by_short_name (param)
		collection.find("address_components.short_name"=>param)
	end

	def self.to_places(params)
		places = []
		params.each do |r|
			places.push(Place.new(r))
		end
		
		return places
	end

	def self.find(id)
		if !id.nil?
		   place = Place.collection.find(:_id=>BSON::ObjectId.from_string(id)).first
		end
		if !place.nil?
			return Place.new(place)
		end
	end

	def self.all(skip=0, limit=nil)
		places = self.collection.find.skip(skip)
		places = places.limit(limit) if !limit.nil?
		results=[]
		places.each do |r|
			results.push(Place.new(r))
		end
		return results
	end

	def destroy
		self.class.collection.find(:_id=>BSON::ObjectId.from_string(@id)).delete_one()
	end

	def self.get_address_components(sort=nil, skip=0, limit = nil)
		if sort.nil?
			sort = {:_id=>1 } 
		end
		if !limit.nil?
			return Place.collection.find.aggregate([{:$sort => sort},
										 {:$project => {:_id=> 1, :formatted_address=>1 , :address_components=>1, "geometry.geolocation":1}}, 
										 {:$unwind=> '$address_components'},
										 {:$skip =>skip}, 
										 {:$limit => limit } ])
		else
			return Place.collection.find.aggregate([{:$sort => sort},
										 {:$project => {:_id=> 1, :formatted_address=>1 , :address_components=>1,"geometry.geolocation":1}}, 
										 {:$skip =>skip},
										 {:$unwind=> '$address_components'} ])
		end

	end


	def self.get_country_names
		
		p = Place.collection.find.aggregate([{:$unwind => '$address_components'},
			{:$project => {:_id=>0, "address_components.long_name"=>1, "address_components.types"=>1} }, 
			{:$unwind => '$address_components.types'},
		 	{:$match=>{"address_components.types":'country'}},
		 	{:$group => {:_id=>"$address_components.long_name"}}])
	
		return p.to_a.map {|r| r[:_id]}
	end

	def self.find_ids_by_country_code (country_code)
		places = Place.collection.find.aggregate([ {:$unwind => "$address_components"},
										  {:$match => {"address_components.short_name":country_code}},
										  {:$project => {:_id=>1}} ])
		return places.map {|doc| doc[:_id].to_s}
	end

#--------------
	#Geolocation
	def self.create_indexes
		collection.indexes.create_one({"geometry.geolocation":Mongo::Index::GEO2DSPHERE})
	end

	def self.remove_indexes
		collection.indexes.drop_one("geometry.geolocation_2dsphere")
	end

	def self.near(point, max_meter=nil)
		my_point = Point.new(point.to_hash)
		return Place.collection.find("geometry.geolocation":{:$near => 
						 {:$geometry => {:type=>"Point", :coordinates=>[my_point.longitude, my_point.latitude] },
						  :$maxDistance=>max_meter}} )
	end

	def near(max_meter=nil)
		places=[]
		@latitude = @location.latitude
		@longitude = @location.longitude
		return self.class.to_places(self.class.collection.find("geometry.geolocation":{:$near => 
						 {:$geometry => {:type=>"Point", :coordinates=>[@longitude, @latitude] },
						  :$maxDistance=>max_meter}} ))
	end

	def photos(offset=0, limit=nil)
		photos=Photo.find_photos_for_place(@id).skip(offset)
		photos = photos.limit(limit) if !limit.nil?
		return photos.find.map {|doc| Photo.new(doc) }
	end

end

#  Place.collection.delete_many
#       Place.load_all(File.open("./db/places.json"))
#       #clear grid fs db
#       Photo.mongo_client.database.fs.find.each { |p| 
#         Photo.mongo_client.database.fs.find(:_id=>p[:_id]).delete_one
#       }
#       #reload db with application images
#       (1..6).each { |n|
#         p = Photo.new 
#         f = File.open("./db/image#{n}.jpg",'rb')
#         p.contents = f
#         id = p.save
#       }    
# Photo.all.each { |photo| 
#         photo.place = photo.find_nearest_place_id(100*1069.34)
#         photo.save
       
#       }






									   

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:formatted_address)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :formatted_address %><br>
    <%= f.text_field :formatted_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Formatted address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
    <% photo=place.photos.sample %>
      <tr>
        <td><%= place.formatted_address %></td>
        <td><%= link_to 'Show', place %></td>
        <% if photo %>
          <td><img height="50px" width="65px" src= <%= photos_show_path("#{photo.id}")%>/></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Formatted address:</strong>
  <%= @place.formatted_address %>
</p>

<% @place.photos.each do |photo| %>
  <p>
    <img height="500px" width="650px" src= <%= photos_show_path("#{photo.id}")%>/>
  </p>
<% end %>

<%= link_to 'Back', places_path %>